<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\assets\BlazorRampKey.snk</AssemblyOriginatorKeyFile>
    <Title>BlazorRamp.ToggleTip</Title>
    <Authors>Paul Kent</Authors>
    <Copyright>Copyright (c) 2026 Paul Kent and BlazorRamp Contributors</Copyright>
    <PackageProjectUrl>https://github.com/BlazorRamp/Components</PackageProjectUrl>
    <RepositoryUrl>https://github.com/BlazorRamp/Components</RepositoryUrl>
    <PackageTags>Blazor; Accessible Components; Accessibility; ARIA; ToggleTip; Information; Dialog</PackageTags>
    <PackageReleaseNotes>Readme changes</PackageReleaseNotes>
    <Description>A ToggleTip component for the Blazor Ramp ecosystem. Technically, this is a non-modal dialog
for displaying supplimental information, activated by click, keyobard, touch or voice.
</Description>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
	  <Version>1.0.1</Version>
	  <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	  <Deterministic>true</Deterministic>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <PackageLicenseFile>LICENSE</PackageLicenseFile>
	  <PackageReadmeFile>README.md</PackageReadmeFile>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="compilerconfig.json" />
	</ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="BuildWebCompiler2022" Version="1.14.15">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    <PackageReference Include="BlazorRamp.Core" Version="1.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.24" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\css\" />
  </ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="BlazorRamp.ToggleTip.Tests.Unit" key="002400000480000094000000060200000024000052534131000400000100010091764439b057aa648d9b6fae0af179aacf637c9e9eb0c53eb2d2480ebc4eadc7ad2cc8ddaca110281c6da8f466eea56e22ce7f6cada84d657f1b2e4a6c5169a03c7e272c3bc7b14930364f0c1a5c5a75a8631dd303454f3569bf32a95db99132838602a24d64b3b92124827682ee19d6df5921a6bc4bd77a999b26c9420337df" />
	</ItemGroup>


	<!-- section to test settings -->

	<!-- This stop the static errors but then stops just pressing save and seeing css changes.-->
	<!--<Target Name="PreResolveProjectStaticWebAssets" BeforeTargets="ResolveProjectStaticWebAssets">
		<ItemGroup>
			<StashedContent Include="@(Content)" />
			<Content Remove="@(Content)" />
		</ItemGroup>
	</Target>
	<Target Name="PostResolveProjectStaticWebAssets" AfterTargets="ResolveProjectStaticWebAssets">
		<ItemGroup>
			<Content Include="@(StashedContent)" />
		</ItemGroup>
	</Target>-->
</Project>
