<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\assets\BlazorRampKey.snk</AssemblyOriginatorKeyFile>
    <PackageId>$(AssemblyName)</PackageId>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Title>BlazorRamp.SkipTo</Title>
    <Authors>Paul Kent</Authors>
    <Description>Provides a Skip To content component for the Blazor Ramp ecosystem of accessible components.</Description>
    <Copyright>Copyright (c) 2025 Paul Kent and BlazorRamp Contributors</Copyright>
    <PackageProjectUrl>https://github.com/BlazorRamp/Components</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/BlazorRamp/Components</RepositoryUrl>
    <PackageTags>Blazor; Accessible Components; Accessibility; ARIA; Live Region;, Skip To content</PackageTags>
    <PackageReleaseNotes>Version 1 fo the Skip To component for the Blazor Ramp ecosystem of accessible components </PackageReleaseNotes>
	<AssemblyVersion>1.0.0</AssemblyVersion>
	<FileVersion>1.0.0</FileVersion>
	<Version>1.0.0</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	 <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Scss\_root_skip_to.scss" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="BuildWebCompiler2022" Version="1.14.15">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.23" />
    <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="compilerconfig.json" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\BlazorRamp.Core\BlazorRamp.Core\BlazorRamp.Core.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<None Update="tsconfig.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</None>
		<Content Update="tsconfig.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="wwwroot\assets\css\" />
	  <Folder Include="wwwroot\assets\js\" />
	</ItemGroup>
	
	<!-- tests -->

</Project>
