// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace BlazorRamp.Tooltip.Components;

public partial class Tooltip
{
    [Parameter] public RenderFragment? ChildContent { get; set; } = null;
}
