<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\..\..\assets\BlazorRampKey.snk</AssemblyOriginatorKeyFile>
    <Title>BlazorRamp.DialogFramework</Title>
    <Authors>Paul Kent</Authors>
    <Description>Modal dialog for the Blazor Ramp ecosystem of accessible Blazor components</Description>
    <Copyright>Copyright (c) 2026 Paul Kent and BlazorRamp Contributors</Copyright>
    <RepositoryUrl>https://github.com/BlazorRamp/Components</RepositoryUrl>
    <PackageProjectUrl>https://github.com/BlazorRamp/Components</PackageProjectUrl>
    <PackageTags>Blazor; Accessible Components; Accessibility; ARIA; Modal dialog; Modal; Dialog;</PackageTags>
    <PackageReleaseNotes>Initial release of the Blazor Ramp modal dialog framework</PackageReleaseNotes>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>


	<ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BuildWebCompiler2022" Version="1.14.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.23" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
    <Folder Include="wwwroot\assets\css\" />
    <Folder Include="wwwroot\assets\js\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlazorRamp.Core\BlazorRamp.Core\BlazorRamp.Core.csproj" />
  </ItemGroup>

</Project>
