<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\..\assets\BlazorRampKey.snk</AssemblyOriginatorKeyFile>
		<Title>BlazorRamp.Core</Title>
		<Copyright>Copyright (c) 2026 Paul Kent and BlazorRamp Contributors</Copyright>
		<PackageProjectUrl>https://github.com/BlazorRamp/Components</PackageProjectUrl>
		<RepositoryUrl>https://github.com/BlazorRamp/Components</RepositoryUrl>
		<PackageTags>Blazor; Accessible Components; Accessibility;CSS Classes;</PackageTags>
		<PackageReleaseNotes>Initial release of the Blazor Ramp Css Classes.	</PackageReleaseNotes>
		<GenerateDocumentationFile>False</GenerateDocumentationFile>
		<AssemblyVersion>1.0.0</AssemblyVersion>
		<FileVersion>1.0.0</FileVersion>
		<Version>1.0.0</Version>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<Authors>Paul Kent</Authors>
		<PackageId>$(AssemblyName)</PackageId>
		<Description>A set of css classes that use the same underlying Blazor Ramp Core projects CSS variables.</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="compilerconfig.json" />
	</ItemGroup>
	
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BlazorRamp.Core" Version="1.1.6" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.29" />
		<PackageReference Include="BuildWebCompiler2022" Version="1.14.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
  </ItemGroup>

</Project>
