<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>..\..\..\assets\BlazorRampKey.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BlazorRamp.Accordion" Version="1.0.0" />
		<PackageReference Include="BlazorRamp.BusyIndicator" Version="1.0.2" />
		<PackageReference Include="BlazorRamp.Core" Version="1.0.8" />
		<PackageReference Include="BlazorRamp.DialogFramework" Version="1.0.2" />
		<PackageReference Include="BlazorRamp.NavGroup" Version="1.0.2" />
		<PackageReference Include="BlazorRamp.SkipTo" Version="1.0.3" />
		<PackageReference Include="BlazorRamp.Switch" Version="1.0.0" />
		<PackageReference Include="BlazorRamp.Tabs" Version="1.0.0" />
		<PackageReference Include="BlazorRamp.ToggleTip" Version="1.0.2" />
		<PackageReference Include="BuildWebCompiler2022" Version="1.14.15" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.8" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.8" PrivateAssets="all" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="6.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Validated.Blazor" Version="1.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\assets\js\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\BlazorRamp.Inputs\BlazorRamp.Inputs\BlazorRamp.Inputs.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="tsconfig.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</None>
		<Content Update="tsconfig.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</Content>
	</ItemGroup>
</Project>
